//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberErp.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class corePositionClass
    {
        public corePositionClass()
        {
            this.corePosition = new HashSet<corePosition>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public int TypeId { get; set; }
        public int CategoryId { get; set; }
        public int SalaryScaleId { get; set; }
        public int PreferredGenderId { get; set; }
        public Nullable<int> MinimumAge { get; set; }
        public Nullable<int> MaximumAge { get; set; }
        public Nullable<decimal> MonthlyWorkingHours { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] LastUpdated { get; set; }
    
        public virtual ICollection<corePosition> corePosition { get; set; }
    }
}
