//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberErp.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class coreRole
    {
        public coreRole()
        {
            this.coreRolePermission = new HashSet<coreRolePermission>();
            this.iffsOperationStatusTemplate = new HashSet<iffsOperationStatusTemplate>();
            this.iffsRoleSetting = new HashSet<iffsRoleSetting>();
            this.coreUserRole = new HashSet<coreUserRole>();
            this.iffsContainerStatusTemplate = new HashSet<iffsContainerStatusTemplate>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] LastUpdated { get; set; }
    
        public virtual ICollection<coreRolePermission> coreRolePermission { get; set; }
        public virtual ICollection<iffsOperationStatusTemplate> iffsOperationStatusTemplate { get; set; }
        public virtual ICollection<iffsRoleSetting> iffsRoleSetting { get; set; }
        public virtual ICollection<coreUserRole> coreUserRole { get; set; }
        public virtual ICollection<iffsContainerStatusTemplate> iffsContainerStatusTemplate { get; set; }
    }
}
