//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberErp.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class corePerson
    {
        public corePerson()
        {
            this.hrmsEmployee = new HashSet<hrmsEmployee>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string FirstNameA { get; set; }
        public string FatherName { get; set; }
        public string FatherNameA { get; set; }
        public string GrandFatherName { get; set; }
        public string GrandFatherNameA { get; set; }
        public int GenderId { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] LastUpdated { get; set; }
    
        public virtual ICollection<hrmsEmployee> hrmsEmployee { get; set; }
    }
}
