//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberErp.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrmsEmployee
    {
        public hrmsEmployee()
        {
            this.iffsApprover = new HashSet<iffsApprover>();
            this.iffsJobOrderHeader = new HashSet<iffsJobOrderHeader>();
            this.iffsJobOrderHeader1 = new HashSet<iffsJobOrderHeader>();
            this.iffsJobOrderHeader2 = new HashSet<iffsJobOrderHeader>();
            this.iffsJobOrderHistoryHeader = new HashSet<iffsJobOrderHistoryHeader>();
            this.iffsJobOrderHistoryHeader1 = new HashSet<iffsJobOrderHistoryHeader>();
            this.iffsJobOrderHistoryHeader2 = new HashSet<iffsJobOrderHistoryHeader>();
            this.iffsOperation = new HashSet<iffsOperation>();
            this.iffsOperation1 = new HashSet<iffsOperation>();
            this.iffsOperation2 = new HashSet<iffsOperation>();
            this.iffsOperation3 = new HashSet<iffsOperation>();
            this.iffsOperation4 = new HashSet<iffsOperation>();
            this.iffsOperation5 = new HashSet<iffsOperation>();
            this.iffsOperation6 = new HashSet<iffsOperation>();
            this.iffsOperation7 = new HashSet<iffsOperation>();
            this.iffsQuotationHeader = new HashSet<iffsQuotationHeader>();
            this.iffsQuotationHeader1 = new HashSet<iffsQuotationHeader>();
            this.iffsQuotationHeader2 = new HashSet<iffsQuotationHeader>();
            this.iffsServiceRequest = new HashSet<iffsServiceRequest>();
            this.iffsServiceRequest1 = new HashSet<iffsServiceRequest>();
            this.iffsServiceRequest2 = new HashSet<iffsServiceRequest>();
            this.iffsInvoiceHeader = new HashSet<iffsInvoiceHeader>();
            this.iffsInvoiceHeader1 = new HashSet<iffsInvoiceHeader>();
            this.iffsInvoiceHeader2 = new HashSet<iffsInvoiceHeader>();
            this.iffsCrateAndBoxRequestHeader = new HashSet<iffsCrateAndBoxRequestHeader>();
            this.iffsCrateAndBoxRequestHeader1 = new HashSet<iffsCrateAndBoxRequestHeader>();
            this.iffsPackingDamageReportHeader = new HashSet<iffsPackingDamageReportHeader>();
            this.iffsPackingDetail = new HashSet<iffsPackingDetail>();
            this.iffsPackingHeader = new HashSet<iffsPackingHeader>();
            this.iffsPackingMaterialHeader = new HashSet<iffsPackingMaterialHeader>();
            this.iffsPackingMaterialHeader1 = new HashSet<iffsPackingMaterialHeader>();
            this.iffsPackingMaterialHeader2 = new HashSet<iffsPackingMaterialHeader>();
            this.iffsSurveyRequest = new HashSet<iffsSurveyRequest>();
            this.iffsSchedule = new HashSet<iffsSchedule>();
            this.iffsPackingSurveyHeader = new HashSet<iffsPackingSurveyHeader>();
        }
    
        public int Id { get; set; }
        public int PersonId { get; set; }
        public Nullable<int> SubsidiaryAccountId { get; set; }
        public string IdentityNumber { get; set; }
        public int NationalityId { get; set; }
        public int MaritalStatusId { get; set; }
        public int ReligionId { get; set; }
        public int EthnicityId { get; set; }
        public int EmploymentTypeId { get; set; }
        public int EmploymentNatureId { get; set; }
        public int PositionId { get; set; }
        public int SalaryScaleId { get; set; }
        public Nullable<decimal> PrevSalary { get; set; }
        public decimal Salary { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string MotherFullName { get; set; }
        public string BirthLocation { get; set; }
        public System.DateTime EmploymentDate { get; set; }
        public string PensionNumber { get; set; }
        public System.DateTime RetirementDate { get; set; }
        public bool HasBirthCertificate { get; set; }
        public bool HasMarriageCertificate { get; set; }
        public bool IsUnderProbation { get; set; }
        public bool IsTerminated { get; set; }
        public string Photo { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] LastUpdated { get; set; }
        public Nullable<int> FundTypeId { get; set; }
        public Nullable<System.DateTime> ProbationDate { get; set; }
    
        public virtual corePerson corePerson { get; set; }
        public virtual corePosition corePosition { get; set; }
        public virtual ICollection<iffsApprover> iffsApprover { get; set; }
        public virtual ICollection<iffsJobOrderHeader> iffsJobOrderHeader { get; set; }
        public virtual ICollection<iffsJobOrderHeader> iffsJobOrderHeader1 { get; set; }
        public virtual ICollection<iffsJobOrderHeader> iffsJobOrderHeader2 { get; set; }
        public virtual ICollection<iffsJobOrderHistoryHeader> iffsJobOrderHistoryHeader { get; set; }
        public virtual ICollection<iffsJobOrderHistoryHeader> iffsJobOrderHistoryHeader1 { get; set; }
        public virtual ICollection<iffsJobOrderHistoryHeader> iffsJobOrderHistoryHeader2 { get; set; }
        public virtual ICollection<iffsOperation> iffsOperation { get; set; }
        public virtual ICollection<iffsOperation> iffsOperation1 { get; set; }
        public virtual ICollection<iffsOperation> iffsOperation2 { get; set; }
        public virtual ICollection<iffsOperation> iffsOperation3 { get; set; }
        public virtual ICollection<iffsOperation> iffsOperation4 { get; set; }
        public virtual ICollection<iffsOperation> iffsOperation5 { get; set; }
        public virtual ICollection<iffsOperation> iffsOperation6 { get; set; }
        public virtual ICollection<iffsOperation> iffsOperation7 { get; set; }
        public virtual ICollection<iffsQuotationHeader> iffsQuotationHeader { get; set; }
        public virtual ICollection<iffsQuotationHeader> iffsQuotationHeader1 { get; set; }
        public virtual ICollection<iffsQuotationHeader> iffsQuotationHeader2 { get; set; }
        public virtual ICollection<iffsServiceRequest> iffsServiceRequest { get; set; }
        public virtual ICollection<iffsServiceRequest> iffsServiceRequest1 { get; set; }
        public virtual ICollection<iffsServiceRequest> iffsServiceRequest2 { get; set; }
        public virtual ICollection<iffsInvoiceHeader> iffsInvoiceHeader { get; set; }
        public virtual ICollection<iffsInvoiceHeader> iffsInvoiceHeader1 { get; set; }
        public virtual ICollection<iffsInvoiceHeader> iffsInvoiceHeader2 { get; set; }
        public virtual ICollection<iffsCrateAndBoxRequestHeader> iffsCrateAndBoxRequestHeader { get; set; }
        public virtual ICollection<iffsCrateAndBoxRequestHeader> iffsCrateAndBoxRequestHeader1 { get; set; }
        public virtual ICollection<iffsPackingDamageReportHeader> iffsPackingDamageReportHeader { get; set; }
        public virtual ICollection<iffsPackingDetail> iffsPackingDetail { get; set; }
        public virtual ICollection<iffsPackingHeader> iffsPackingHeader { get; set; }
        public virtual ICollection<iffsPackingMaterialHeader> iffsPackingMaterialHeader { get; set; }
        public virtual ICollection<iffsPackingMaterialHeader> iffsPackingMaterialHeader1 { get; set; }
        public virtual ICollection<iffsPackingMaterialHeader> iffsPackingMaterialHeader2 { get; set; }
        public virtual ICollection<iffsSurveyRequest> iffsSurveyRequest { get; set; }
        public virtual ICollection<iffsSchedule> iffsSchedule { get; set; }
        public virtual ICollection<iffsPackingSurveyHeader> iffsPackingSurveyHeader { get; set; }
    }
}
