//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberErp.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class iffsServiceRequestDetail
    {
        public iffsServiceRequestDetail()
        {
            this.iffsQuotationDetail = new HashSet<iffsQuotationDetail>();
        }
    
        public int Id { get; set; }
        public int HeaderId { get; set; }
        public int OperationTypeId { get; set; }
        public Nullable<int> CommodityTypeId { get; set; }
        public decimal Volume { get; set; }
        public decimal Weight { get; set; }
        public string Pcs { get; set; }
        public Nullable<int> ContainerTypeId { get; set; }
        public string POE { get; set; }
        public string POD { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] LastUpdated { get; set; }
        public string Description { get; set; }
        public string TareWeight { get; set; }
    
        public virtual iffsLupCommodityType iffsLupCommodityType { get; set; }
        public virtual iffsLupContainerType iffsLupContainerType { get; set; }
        public virtual iffsLupOperationType iffsLupOperationType { get; set; }
        public virtual ICollection<iffsQuotationDetail> iffsQuotationDetail { get; set; }
        public virtual iffsServiceRequest iffsServiceRequest { get; set; }
    }
}
