//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberErp.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class iffsOperationStatus
    {
        public int Id { get; set; }
        public int OperationId { get; set; }
        public int StatusId { get; set; }
        public string Value { get; set; }
        public string Remark { get; set; }
        public byte[] LastUpdated { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual iffsOperationStatusTemplate iffsOperationStatusTemplate { get; set; }
        public virtual iffsOperation iffsOperation { get; set; }
    }
}
