//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberErp.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class iffsNotification
    {
        public int Id { get; set; }
        public string Operation { get; set; }
        public int ObjectId { get; set; }
        public int ActorId { get; set; }
        public System.DateTime Date { get; set; }
        public string Message { get; set; }
        public bool IsViewed { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] LastUpdated { get; set; }
    }
}
