//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberErp.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class iffsSurveyRequest
    {
        public iffsSurveyRequest()
        {
            this.iffsCrateAndBoxRequestHeader = new HashSet<iffsCrateAndBoxRequestHeader>();
            this.iffsPackingHeader = new HashSet<iffsPackingHeader>();
            this.iffsPackingMaterialHeader = new HashSet<iffsPackingMaterialHeader>();
            this.iffsPackingSurveyHeader = new HashSet<iffsPackingSurveyHeader>();
        }
    
        public int Id { get; set; }
        public string Number { get; set; }
        public int OrderingClientId { get; set; }
        public int ReceivingClientId { get; set; }
        public System.DateTime ProposedSurveyDate { get; set; }
        public string SurveyLocation { get; set; }
        public System.DateTime ProposedPackingDate { get; set; }
        public string OriginCity { get; set; }
        public string DestinationCityCountry { get; set; }
        public decimal ClientAllowanceVolume { get; set; }
        public string MeasurmentUnit { get; set; }
        public string HandlingAgent { get; set; }
        public string AdditionalInstruction { get; set; }
        public System.DateTime SurveyReportDate { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<System.DateTime> ScheduleDate { get; set; }
        public int PreparedById { get; set; }
        public Nullable<int> AirLineId { get; set; }
        public Nullable<int> ShippingLineId { get; set; }
        public Nullable<int> RailWayId { get; set; }
        public bool IsAir { get; set; }
        public bool IsOcean { get; set; }
        public bool IsRailWay { get; set; }
        public bool IsViewed { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] LastUpdated { get; set; }
    
        public virtual hrmsEmployee hrmsEmployee { get; set; }
        public virtual ICollection<iffsCrateAndBoxRequestHeader> iffsCrateAndBoxRequestHeader { get; set; }
        public virtual iffsCustomer iffsCustomer { get; set; }
        public virtual ICollection<iffsPackingHeader> iffsPackingHeader { get; set; }
        public virtual ICollection<iffsPackingMaterialHeader> iffsPackingMaterialHeader { get; set; }
        public virtual iffsReceivingClient iffsReceivingClient { get; set; }
        public virtual iffsShipmentType iffsShipmentTypeAirLIne { get; set; }
        public virtual iffsShipmentType iffsShipmentTypeRailWay { get; set; }
        public virtual iffsShipmentType iffsShipmentTypeShippingIne { get; set; }
        public virtual ICollection<iffsPackingSurveyHeader> iffsPackingSurveyHeader { get; set; }
    }
}
