//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberErp.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class iffsJobOrderHeader
    {
        public iffsJobOrderHeader()
        {
            this.iffsJobOrderDetail = new HashSet<iffsJobOrderDetail>();
            this.iffsJobOrderDocument = new HashSet<iffsJobOrderDocument>();
            this.iffsJobOrderQuotation = new HashSet<iffsJobOrderQuotation>();
            this.iffsOperation = new HashSet<iffsOperation>();
        }
    
        public int Id { get; set; }
        public string Quotations { get; set; }
        public string JobOrderNo { get; set; }
        public int OperationTypeId { get; set; }
        public Nullable<int> ParentJobOrderId { get; set; }
        public string Version { get; set; }
        public Nullable<System.DateTime> ValidityDate { get; set; }
        public string UltimateClient { get; set; }
        public string ReceivingClient { get; set; }
        public string ContactPersonLocal { get; set; }
        public string ContactPersonForeign { get; set; }
        public int PreparedById { get; set; }
        public System.DateTime PreparedDate { get; set; }
        public Nullable<int> CheckedById { get; set; }
        public Nullable<System.DateTime> CheckedDate { get; set; }
        public Nullable<int> ApprovedById { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsViewed { get; set; }
        public string Remark { get; set; }
        public bool IsRequiredDocumentsSubmited { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] LastUpdated { get; set; }
    
        public virtual hrmsEmployee hrmsEmployee { get; set; }
        public virtual hrmsEmployee hrmsEmployee1 { get; set; }
        public virtual hrmsEmployee hrmsEmployee2 { get; set; }
        public virtual ICollection<iffsJobOrderDetail> iffsJobOrderDetail { get; set; }
        public virtual ICollection<iffsJobOrderDocument> iffsJobOrderDocument { get; set; }
        public virtual iffsLupOperationType iffsLupOperationType { get; set; }
        public virtual ICollection<iffsJobOrderQuotation> iffsJobOrderQuotation { get; set; }
        public virtual ICollection<iffsOperation> iffsOperation { get; set; }
    }
}
