//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberErp.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class iffsPackingList
    {
        public int Id { get; set; }
        public int OperationId { get; set; }
        public int HeaderId { get; set; }
        public string Description { get; set; }
        public int CartonNumber { get; set; }
        public decimal Weight { get; set; }
        public int CrateNumber { get; set; }
        public string Value { get; set; }
        public int LabelId { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] LastUpdated { get; set; }
    
        public virtual iffsLupDamageType iffsLupDamageType { get; set; }
        public virtual iffsOperation iffsOperation { get; set; }
        public virtual iffsPackingHeader iffsPackingHeader { get; set; }
    }
}
