//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberErp.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class iffsServiceRequest
    {
        public iffsServiceRequest()
        {
            this.iffsQuotationHeader = new HashSet<iffsQuotationHeader>();
            this.iffsServiceRequestDetail = new HashSet<iffsServiceRequestDetail>();
            this.iffsServiceRequestDocuments = new HashSet<iffsServiceRequestDocuments>();
        }
    
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public System.DateTime RequestDate { get; set; }
        public string RequestNo { get; set; }
        public string RequesterFirstName { get; set; }
        public string RequesterLastName { get; set; }
        public string Address { get; set; }
        public string CommodityType { get; set; }
        public string CommodityDescription { get; set; }
        public int PreparedById { get; set; }
        public System.DateTime PreparedDate { get; set; }
        public Nullable<int> CheckedById { get; set; }
        public Nullable<System.DateTime> CheckedDate { get; set; }
        public Nullable<int> ApprovedById { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public bool CanBeHandled { get; set; }
        public Nullable<System.DateTime> ResponseDate { get; set; }
        public bool HasAgreement { get; set; }
        public Nullable<int> ServiceAgreementId { get; set; }
        public string Remark { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] LastUpdated { get; set; }
    
        public virtual hrmsEmployee hrmsEmployee { get; set; }
        public virtual hrmsEmployee hrmsEmployee1 { get; set; }
        public virtual hrmsEmployee hrmsEmployee2 { get; set; }
        public virtual iffsCustomer iffsCustomer { get; set; }
        public virtual ICollection<iffsQuotationHeader> iffsQuotationHeader { get; set; }
        public virtual iffsServiceAgreement iffsServiceAgreement { get; set; }
        public virtual ICollection<iffsServiceRequestDetail> iffsServiceRequestDetail { get; set; }
        public virtual ICollection<iffsServiceRequestDocuments> iffsServiceRequestDocuments { get; set; }
    }
}
