//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberErp.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class iffsPackingMaterialConsumption
    {
        public int Id { get; set; }
        public int HeaderId { get; set; }
        public int PackingMaterialId { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Requested { get; set; }
        public decimal Returned { get; set; }
        public decimal Consumed { get; set; }
        public string Remarks { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] LastUpdated { get; set; }
    
        public virtual iffsPackingHeader iffsPackingHeader { get; set; }
        public virtual iffsPackingMaterialDetail iffsPackingMaterialDetail { get; set; }
    }
}
