//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberErp.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class iffsDocumentNoSetting
    {
        public int Id { get; set; }
        public string DocumentType { get; set; }
        public string Prefix { get; set; }
        public string SurFix { get; set; }
        public Nullable<int> Year { get; set; }
        public int CurrentNo { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] LastUpdated { get; set; }
        public int NoOfDigit { get; set; }
    }
}
