//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberErp.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class iffsLupOperationType
    {
        public iffsLupOperationType()
        {
            this.iffsJobOrderTemplate = new HashSet<iffsJobOrderTemplate>();
            this.iffsOperationDocumentTemplate = new HashSet<iffsOperationDocumentTemplate>();
            this.iffsOperationStatusTemplate = new HashSet<iffsOperationStatusTemplate>();
            this.iffsQuotationDetail = new HashSet<iffsQuotationDetail>();
            this.iffsQuotationTemplate = new HashSet<iffsQuotationTemplate>();
            this.iffsUserOperationTypeMapping = new HashSet<iffsUserOperationTypeMapping>();
            this.iffsOperationExpenseTemplate = new HashSet<iffsOperationExpenseTemplate>();
            this.iffsServiceRequestDetail = new HashSet<iffsServiceRequestDetail>();
            this.iffsServiceRate = new HashSet<iffsServiceRate>();
            this.iffsJobOrderHeader = new HashSet<iffsJobOrderHeader>();
            this.iffsJobOrderHistoryHeader = new HashSet<iffsJobOrderHistoryHeader>();
            this.iffsInvoiceHeader = new HashSet<iffsInvoiceHeader>();
            this.iffsContainerStatusTemplate = new HashSet<iffsContainerStatusTemplate>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] LastUpdated { get; set; }
    
        public virtual ICollection<iffsJobOrderTemplate> iffsJobOrderTemplate { get; set; }
        public virtual ICollection<iffsOperationDocumentTemplate> iffsOperationDocumentTemplate { get; set; }
        public virtual ICollection<iffsOperationStatusTemplate> iffsOperationStatusTemplate { get; set; }
        public virtual ICollection<iffsQuotationDetail> iffsQuotationDetail { get; set; }
        public virtual ICollection<iffsQuotationTemplate> iffsQuotationTemplate { get; set; }
        public virtual ICollection<iffsUserOperationTypeMapping> iffsUserOperationTypeMapping { get; set; }
        public virtual ICollection<iffsOperationExpenseTemplate> iffsOperationExpenseTemplate { get; set; }
        public virtual ICollection<iffsServiceRequestDetail> iffsServiceRequestDetail { get; set; }
        public virtual ICollection<iffsServiceRate> iffsServiceRate { get; set; }
        public virtual ICollection<iffsJobOrderHeader> iffsJobOrderHeader { get; set; }
        public virtual ICollection<iffsJobOrderHistoryHeader> iffsJobOrderHistoryHeader { get; set; }
        public virtual ICollection<iffsInvoiceHeader> iffsInvoiceHeader { get; set; }
        public virtual ICollection<iffsContainerStatusTemplate> iffsContainerStatusTemplate { get; set; }
    }
}
