//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberErp.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class iffsServiceAgreement
    {
        public iffsServiceAgreement()
        {
            this.iffsServiceRequest = new HashSet<iffsServiceRequest>();
        }
    
        public int Id { get; set; }
        public string AgreementNo { get; set; }
        public System.DateTime Date { get; set; }
        public int CustomerId { get; set; }
        public Nullable<int> QuotationId { get; set; }
        public string AgreementFile { get; set; }
        public string Remark { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] LastUpdated { get; set; }
    
        public virtual iffsCustomer iffsCustomer { get; set; }
        public virtual iffsQuotationHeader iffsQuotationHeader { get; set; }
        public virtual ICollection<iffsServiceRequest> iffsServiceRequest { get; set; }
    }
}
