//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberErp.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class iffsLupCurrency
    {
        public iffsLupCurrency()
        {
            this.iffsQuotationDetail = new HashSet<iffsQuotationDetail>();
            this.iffsOperationExpense = new HashSet<iffsOperationExpense>();
            this.iffsServiceRate = new HashSet<iffsServiceRate>();
            this.iffsContainer = new HashSet<iffsContainer>();
            this.iffsInvoiceDetail = new HashSet<iffsInvoiceDetail>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] LastUpdated { get; set; }
    
        public virtual ICollection<iffsQuotationDetail> iffsQuotationDetail { get; set; }
        public virtual ICollection<iffsOperationExpense> iffsOperationExpense { get; set; }
        public virtual ICollection<iffsServiceRate> iffsServiceRate { get; set; }
        public virtual ICollection<iffsContainer> iffsContainer { get; set; }
        public virtual ICollection<iffsInvoiceDetail> iffsInvoiceDetail { get; set; }
    }
}
