//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberErp.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class iffsPackingMaterialHeader
    {
        public iffsPackingMaterialHeader()
        {
            this.iffsPackingMaterialDetail = new HashSet<iffsPackingMaterialDetail>();
        }
    
        public int Id { get; set; }
        public string Number { get; set; }
        public int SurveyId { get; set; }
        public System.DateTime RequestedDate { get; set; }
        public string RequestedDept { get; set; }
        public string ToDept { get; set; }
        public int PreparedById { get; set; }
        public int OperationId { get; set; }
        public System.DateTime PreparedDate { get; set; }
        public Nullable<int> CheckedById { get; set; }
        public Nullable<System.DateTime> CheckedDate { get; set; }
        public Nullable<int> ApprovedById { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public bool IsViewed { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] LastUpdated { get; set; }
    
        public virtual hrmsEmployee hrmsEmployee { get; set; }
        public virtual hrmsEmployee hrmsEmployee1 { get; set; }
        public virtual hrmsEmployee hrmsEmployee2 { get; set; }
        public virtual iffsOperation iffsOperation { get; set; }
        public virtual ICollection<iffsPackingMaterialDetail> iffsPackingMaterialDetail { get; set; }
        public virtual iffsSurveyRequest iffsSurveyRequest { get; set; }
    }
}
