//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberErp.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class iffsInvoiceOperation
    {
        public int Id { get; set; }
        public int InvoiceHeaderId { get; set; }
        public int OperationId { get; set; }
    
        public virtual iffsOperation iffsOperation { get; set; }
        public virtual iffsInvoiceHeader iffsInvoiceHeader { get; set; }
    }
}
