//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberErp.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class iffsPackingMaterialDetail
    {
        public iffsPackingMaterialDetail()
        {
            this.iffsPackingMaterialConsumption = new HashSet<iffsPackingMaterialConsumption>();
        }
    
        public int Id { get; set; }
        public int HeaderId { get; set; }
        public string Description { get; set; }
        public string GRNNumber { get; set; }
        public int MeasurmentUnit { get; set; }
        public int Qty { get; set; }
        public string Remark { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] LastUpdated { get; set; }
    
        public virtual ICollection<iffsPackingMaterialConsumption> iffsPackingMaterialConsumption { get; set; }
        public virtual iffsPackingMaterialHeader iffsPackingMaterialHeader { get; set; }
        public virtual lupMeasurementUnit lupMeasurementUnit { get; set; }
    }
}
