//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberErp.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class iffsQuotationTemplate
    {
        public int Id { get; set; }
        public Nullable<int> OperationTypeId { get; set; }
        public Nullable<int> ServiceId { get; set; }
    
        public virtual iffsLupOperationType iffsLupOperationType { get; set; }
        public virtual iffsService iffsService { get; set; }
    }
}
