//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberErp.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class iffsLupExpenseType
    {
        public iffsLupExpenseType()
        {
            this.iffsOperationExpenseTemplate = new HashSet<iffsOperationExpenseTemplate>();
            this.iffsOperationExpense = new HashSet<iffsOperationExpense>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] LastUpdated { get; set; }
    
        public virtual ICollection<iffsOperationExpenseTemplate> iffsOperationExpenseTemplate { get; set; }
        public virtual ICollection<iffsOperationExpense> iffsOperationExpense { get; set; }
    }
}
