//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberErp.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class iffsContainerStatusTemplate
    {
        public iffsContainerStatusTemplate()
        {
            this.iffsContainerStatus = new HashSet<iffsContainerStatus>();
        }
    
        public int Id { get; set; }
        public string ContainerStatusType { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public int DataTypeId { get; set; }
        public int RoleId { get; set; }
        public byte[] LastUpdated { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> OperationTypeId { get; set; }
    
        public virtual coreRole coreRole { get; set; }
        public virtual iffsLupDataType iffsLupDataType { get; set; }
        public virtual ICollection<iffsContainerStatus> iffsContainerStatus { get; set; }
        public virtual iffsLupOperationType iffsLupOperationType { get; set; }
    }
}
