//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberErp.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class iffsQuotationHeader
    {
        public iffsQuotationHeader()
        {
            this.iffsJobOrderQuotation = new HashSet<iffsJobOrderQuotation>();
            this.iffsQuotationDetail = new HashSet<iffsQuotationDetail>();
            this.iffsQuotationHeader1 = new HashSet<iffsQuotationHeader>();
            this.iffsQuotationTermandCondition = new HashSet<iffsQuotationTermandCondition>();
            this.iffsServiceAgreement = new HashSet<iffsServiceAgreement>();
        }
    
        public int Id { get; set; }
        public int ServiceRequestId { get; set; }
        public System.DateTime Date { get; set; }
        public string QuotationNo { get; set; }
        public Nullable<int> ParentQuotationId { get; set; }
        public string Version { get; set; }
        public System.DateTime ValidityDate { get; set; }
        public int PreparedById { get; set; }
        public System.DateTime PreparedDate { get; set; }
        public Nullable<int> CheckedById { get; set; }
        public Nullable<System.DateTime> CheckedDate { get; set; }
        public Nullable<int> ApprovedById { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> CustomerResponseDate { get; set; }
        public bool IsAccepted { get; set; }
        public string CustomerResponseRemark { get; set; }
        public Nullable<int> PrevQuotationId { get; set; }
        public string PrevQuotationNumber { get; set; }
    
        public virtual hrmsEmployee hrmsEmployee { get; set; }
        public virtual hrmsEmployee hrmsEmployee1 { get; set; }
        public virtual hrmsEmployee hrmsEmployee2 { get; set; }
        public virtual ICollection<iffsJobOrderQuotation> iffsJobOrderQuotation { get; set; }
        public virtual ICollection<iffsQuotationDetail> iffsQuotationDetail { get; set; }
        public virtual ICollection<iffsQuotationHeader> iffsQuotationHeader1 { get; set; }
        public virtual iffsQuotationHeader iffsQuotationHeader2 { get; set; }
        public virtual iffsQuotationHeader iffsQuotationHeader11 { get; set; }
        public virtual iffsQuotationHeader iffsQuotationHeader3 { get; set; }
        public virtual ICollection<iffsQuotationTermandCondition> iffsQuotationTermandCondition { get; set; }
        public virtual ICollection<iffsServiceAgreement> iffsServiceAgreement { get; set; }
        public virtual iffsServiceRequest iffsServiceRequest { get; set; }
    }
}
