//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberErp.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class iffsOperationExpense
    {
        public int Id { get; set; }
        public int OperationId { get; set; }
        public int ExpenseTypeId { get; set; }
        public decimal Amount { get; set; }
        public int CurrencyId { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public byte[] LastUpdated { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual iffsLupCurrency iffsLupCurrency { get; set; }
        public virtual iffsLupExpenseType iffsLupExpenseType { get; set; }
        public virtual iffsOperation iffsOperation { get; set; }
    }
}
