//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberErp.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class iffsServiceRate
    {
        public int Id { get; set; }
        public int ServiceId { get; set; }
        public Nullable<int> OperationTypeId { get; set; }
        public int ServiceUnitTypeId { get; set; }
        public int CurrencyId { get; set; }
        public decimal Rate { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] LastUpdated { get; set; }
        public string ComparingSign { get; set; }
        public string Description { get; set; }
    
        public virtual iffsLupCurrency iffsLupCurrency { get; set; }
        public virtual iffsLupOperationType iffsLupOperationType { get; set; }
        public virtual iffsLupServiceUnitType iffsLupServiceUnitType { get; set; }
        public virtual iffsService iffsService { get; set; }
    }
}
