//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberErp.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class iffsShipmentType
    {
        public iffsShipmentType()
        {
            this.iffsSurveyRequest = new HashSet<iffsSurveyRequest>();
            this.iffsSurveyRequest1 = new HashSet<iffsSurveyRequest>();
            this.iffsSurveyRequest2 = new HashSet<iffsSurveyRequest>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string Type { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] LastUpdated { get; set; }
    
        public virtual ICollection<iffsSurveyRequest> iffsSurveyRequest { get; set; }
        public virtual ICollection<iffsSurveyRequest> iffsSurveyRequest1 { get; set; }
        public virtual ICollection<iffsSurveyRequest> iffsSurveyRequest2 { get; set; }
    }
}
