//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberErp.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class iffsCustomer
    {
        public iffsCustomer()
        {
            this.iffsServiceAgreement = new HashSet<iffsServiceAgreement>();
            this.iffsServiceRequest = new HashSet<iffsServiceRequest>();
            this.iffsInvoiceHeader = new HashSet<iffsInvoiceHeader>();
            this.iffsPackingDamageReportHeader = new HashSet<iffsPackingDamageReportHeader>();
            this.iffsSurveyRequest = new HashSet<iffsSurveyRequest>();
        }
    
        public int Id { get; set; }
        public int CustomerGroupId { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string TinNo { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] LastUpdated { get; set; }
    
        public virtual iffsLupCustomerGroup iffsLupCustomerGroup { get; set; }
        public virtual ICollection<iffsServiceAgreement> iffsServiceAgreement { get; set; }
        public virtual ICollection<iffsServiceRequest> iffsServiceRequest { get; set; }
        public virtual ICollection<iffsInvoiceHeader> iffsInvoiceHeader { get; set; }
        public virtual ICollection<iffsPackingDamageReportHeader> iffsPackingDamageReportHeader { get; set; }
        public virtual ICollection<iffsSurveyRequest> iffsSurveyRequest { get; set; }
    }
}
