//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberErp.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class iffsPackingMaterial
    {
        public int Id { get; set; }
        public int MaterialId { get; set; }
        public int SurveyId { get; set; }
        public int Quantity { get; set; }
        public string Remark { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] LastUpdated { get; set; }
    
        public virtual iffsPackingMaterialList iffsPackingMaterialList { get; set; }
        public virtual iffsPackingSurveyHeader iffsPackingSurveyHeader { get; set; }
    }
}
