//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberErp.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class iffsPackingHeader
    {
        public iffsPackingHeader()
        {
            this.iffsPackingCrateAndBoxConsumption = new HashSet<iffsPackingCrateAndBoxConsumption>();
            this.iffsPackingDetail = new HashSet<iffsPackingDetail>();
            this.iffsPackingList = new HashSet<iffsPackingList>();
            this.iffsPackingMaterialConsumption = new HashSet<iffsPackingMaterialConsumption>();
            this.iffsPackingTruckAndMachine = new HashSet<iffsPackingTruckAndMachine>();
        }
    
        public int Id { get; set; }
        public int OperationId { get; set; }
        public int SurveyId { get; set; }
        public string ActivityType { get; set; }
        public int SupervisorId { get; set; }
        public decimal EstimatedVolume { get; set; }
        public string ActualVolume { get; set; }
        public decimal ActualWeight { get; set; }
        public int NumberofStaff { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Remark { get; set; }
        public int PreparedBy { get; set; }
        public System.DateTime PreparedDate { get; set; }
        public int LunchProvided { get; set; }
        public string OtherRelatedCost { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] LastUpdated { get; set; }
    
        public virtual hrmsEmployee hrmsEmployee { get; set; }
        public virtual iffsOperation iffsOperation { get; set; }
        public virtual ICollection<iffsPackingCrateAndBoxConsumption> iffsPackingCrateAndBoxConsumption { get; set; }
        public virtual ICollection<iffsPackingDetail> iffsPackingDetail { get; set; }
        public virtual iffsSurveyRequest iffsSurveyRequest { get; set; }
        public virtual ICollection<iffsPackingList> iffsPackingList { get; set; }
        public virtual ICollection<iffsPackingMaterialConsumption> iffsPackingMaterialConsumption { get; set; }
        public virtual ICollection<iffsPackingTruckAndMachine> iffsPackingTruckAndMachine { get; set; }
    }
}
