//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberErp.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class iffsOperationStatusTemplate
    {
        public iffsOperationStatusTemplate()
        {
            this.iffsOperationStatus = new HashSet<iffsOperationStatus>();
        }
    
        public int Id { get; set; }
        public int OperationTypeId { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public int DataTypeId { get; set; }
        public decimal PlannedDuration { get; set; }
        public int RoleId { get; set; }
        public byte[] LastUpdated { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual coreRole coreRole { get; set; }
        public virtual iffsLupDataType iffsLupDataType { get; set; }
        public virtual iffsLupOperationType iffsLupOperationType { get; set; }
        public virtual ICollection<iffsOperationStatus> iffsOperationStatus { get; set; }
    }
}
