//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberErp.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class lupMeasurementUnit
    {
        public lupMeasurementUnit()
        {
            this.iffsPackingMaterialDetail = new HashSet<iffsPackingMaterialDetail>();
            this.iffsPackingMaterialList = new HashSet<iffsPackingMaterialList>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] LastUpdated { get; set; }
    
        public virtual ICollection<iffsPackingMaterialDetail> iffsPackingMaterialDetail { get; set; }
        public virtual ICollection<iffsPackingMaterialList> iffsPackingMaterialList { get; set; }
    }
}
