Ext.ns('Ext.erp.iffs.ux.customer');
/**
* @desc      Customer registration form
* @author    Wondwosen Desalegn
* @copyright (c) 2017, Cybersoft
* @date      November 01, 2017
* @namespace Ext.erp.iffs.ux.customer
* @class     Ext.erp.iffs.ux.customer.Form
* @extends   Ext.form.FormPanel
*/
Ext.erp.iffs.ux.customer.Form = function (config) {
    Ext.erp.iffs.ux.customer.Form.superclass.constructor.call(this, Ext.apply({
        api: {
            load: Customer.Get,
            submit: Customer.Save
        },
        paramOrder: ['id'],
        defaults: {
            anchor: '95%',
            labelStyle: 'text-align:right;',
            msgTarget: 'side'
        },
        id: 'customer-form',
        padding: 5,
        labelWidth: 120,
        autoHeight: true,
        border: false,
        baseCls: 'x-plain',
        items: [{
            name: 'Id',
            xtype: 'hidden'
        }, {
            hiddenName: 'CustomerGroupId',
            xtype: 'combo',
            fieldLabel: 'Customer Group',
            triggerAction: 'all',
            mode: 'local',
            editable: false,
            forceSelection: true,
            emptyText: '---Select---',
            allowBlank: false,
            store: new Ext.data.DirectStore({
                reader: new Ext.data.JsonReader({
                    successProperty: 'success',
                    idProperty: 'Id',
                    root: 'data',
                    fields: ['Id', 'Name', 'Code']
                }),
                autoLoad: true,
                api: { read: Iffs.GetCustomerGroup }
            }),
            valueField: 'Id',
            displayField: 'Name'
        }, {
            name: 'Name',
            xtype: 'textfield',
            fieldLabel: 'Name',
            allowBlank: false
        }, {
            name: 'Code',
            xtype: 'textfield',
            fieldLabel: 'Code',
            readOnly: true,
            
            value: 'AutoGenerated',
            style: 'font-weight: italics; color: grey;'
        }, {
            name: 'TinNo',
            xtype: 'textfield',
            fieldLabel: 'Tin No',
            allowBlank: true
        }, {
            name: 'Email',
            xtype: 'textfield',
            fieldLabel: 'Email',
            allowBlank: true
        }, {
            name: 'Telephone',
            xtype: 'textfield',
            fieldLabel: 'Telephone',
            allowBlank: true
        }, {
            name: 'Address',
            xtype: 'textarea',
            fieldLabel: 'Address',
            allowBlank: false
        }]
    }, config));
};
Ext.extend(Ext.erp.iffs.ux.customer.Form, Ext.form.FormPanel);
Ext.reg('customer-form', Ext.erp.iffs.ux.customer.Form);

/**
* @desc      Customer registration form host window
* @author    Wondwosen Desalegn
* @copyright (c) 2017, Cybersoft
* @date      November 01, 2017
* @namespace Ext.erp.iffs.ux.customer
* @class     Ext.erp.iffs.ux.customer.Window
* @extends   Ext.Window
*/
Ext.erp.iffs.ux.customer.Window = function (config) {
    Ext.erp.iffs.ux.customer.Window.superclass.constructor.call(this, Ext.apply({
        layout: 'fit',
        width: 500,
        autoHeight: true,
        closeAction: 'close',
        modal: true,
        resizable: false,
        buttonAlign: 'right',
        bodyStyle: 'padding:5px;',
        listeners: {
            show: function () {
                this.form.getForm().findField('Id').setValue(this.customerId);
                if (this.customerId != '') {
                    this.form.load({ params: { id: this.customerId } });
                }
            },
            scope: this
        }
    }, config));
};
Ext.extend(Ext.erp.iffs.ux.customer.Window, Ext.Window, {
    initComponent: function () {
        this.form = new Ext.erp.iffs.ux.customer.Form({targetForm:this.targetForm});
        this.items = [this.form];
        this.buttons = [{
            text: 'Save',
            iconCls: 'icon-save',
            handler: this.onSave,
            scope: this
        }, {
            xtype: 'tbseparator'
        }, {
            text: 'Close',
            iconCls: 'icon-exit',
            handler: this.onClose,
            scope: this
        }];
        this.tools = [{
            id: 'refresh',
            qtip: 'Reset',
            handler: function () {
                this.form.getForm().reset();
            },
            scope: this
        }];
        Ext.erp.iffs.ux.customer.Window.superclass.initComponent.call(this, arguments);
    },
    onSave: function () {
        if (!this.form.getForm().isValid()) return;
        this.form.getForm().submit({
            waitMsg: 'Please wait...',
            success: function (form, action) {
                if (typeof form.targetForm != "undefined" && form.targetForm != null) {
                    form.targetForm.findField('CustomerId').setValue(action.result.customerId);
                    form.targetForm.findField('Customer').setValue(Ext.getCmp('customer-form').getForm().findField('Name').getValue());
                    form.targetForm.findField('CustomerGroupId').setValue(Ext.getCmp('customer-form').getForm().findField('CustomerGroupId').getValue());
                    form.targetForm.findField('CustomerGroup').setValue(Ext.getCmp('customer-form').getForm().findField('CustomerGroupId').getRawValue());
                    Ext.MessageBox.show({
                        title: 'Sucess',
                        msg: action.result.data,
                        buttons: Ext.Msg.OK,
                        icon: Ext.MessageBox.SUCCESS,
                        scope: this
                    });
                }
                Ext.getCmp('customer-form').getForm().reset();
                Ext.getCmp('customer-paging').doRefresh();
            },
            failure: function (form, action) {
                Ext.MessageBox.show({
                    title: 'Error',
                    msg: action.result.data,
                    buttons: Ext.Msg.OK,
                    icon: Ext.MessageBox.ERROR,
                    scope: this
                });
            }
        });
    },
    onClose: function () {
        this.close();
    }
});
Ext.reg('customer-window', Ext.erp.iffs.ux.customer.Window);

/**
* @desc      Customer grid
* @author    Wondwosen Desalegn
* @copyright (c) 2017, Cybersoft
* @date      November 01, 2017
* @namespace Ext.erp.iffs.ux.customer
* @class     Ext.erp.iffs.ux.customer.Grid
* @extends   Ext.grid.GridPanel
*/
Ext.erp.iffs.ux.customer.Grid = function (config) {
    Ext.erp.iffs.ux.customer.Grid.superclass.constructor.call(this, Ext.apply({
        store: new Ext.data.DirectStore({
            directFn: Customer.GetAll,
            paramsAsHash: false,
            paramOrder: 'start|limit|sort|dir|record',
            root: 'data',
            idProperty: 'Id',
            totalProperty: 'total',
            sortInfo: {
                field: 'CustomerGroup',
                direction: 'ASC'
            },
            fields: ['Id', 'CustomerGroupId', 'CustomerGroup', 'Name', 'Code', 'TinNo', 'Address', 'Email', 'Telephone'],
            remoteSort: true
        }),
        id: 'customer-grid',
        loadMask: true,
        pageSize: 30,
        stripeRows: true,
        border: false,
        sm: new Ext.grid.RowSelectionModel({
            singleSelect: true
        }),
        columns: [{
            dataIndex: 'Id',
            header: 'Id',
            sortable: true,
            hidden: true,
            width: 100,
            menuDisabled: true
        }, new Ext.grid.RowNumberer(), {
            dataIndex: 'CustomerGroup',
            header: 'Customer Group',
            sortable: true,
            width: 100,
            menuDisabled: true
        }, {
            dataIndex: 'Name',
            header: 'Name',
            sortable: true,
            width: 200,
            menuDisabled: true
        }, {
            dataIndex: 'Code',
            header: 'Code',
            sortable: true,
            width: 100,
            menuDisabled: true
        }, {
            dataIndex: 'TinNo',
            header: 'Tin No.',
            sortable: true,
            width: 100,
            menuDisabled: true
        }, {
            dataIndex: 'Email',
            header: 'Email',
            sortable: true,
            width: 150,
            menuDisabled: true
        }, {
            dataIndex: 'Telephone',
            header: 'Telephone',
            sortable: true,
            width: 150,
            menuDisabled: true
        }, {
            dataIndex: 'Address',
            header: 'Address',
            sortable: true,
            width: 200,
            menuDisabled: true
        }]
    }, config));
};
Ext.extend(Ext.erp.iffs.ux.customer.Grid, Ext.grid.GridPanel, {
    initComponent: function () {
        this.store.baseParams = { record: Ext.encode({ searchText: '' }) };
        this.bbar = new Ext.PagingToolbar({
            id: 'customer-paging',
            store: this.store,
            displayInfo: true,
            pageSize: this.pageSize
        });
        Ext.erp.iffs.ux.customer.Grid.superclass.initComponent.apply(this, arguments);
    },
    afterRender: function () {
        this.getStore().load({
            params: {
                start: 0,
                limit: this.pageSize
            }
        });
        Ext.erp.iffs.ux.customer.Grid.superclass.afterRender.apply(this, arguments);
    }
});
Ext.reg('customer-grid', Ext.erp.iffs.ux.customer.Grid);

/**
* @desc      Customer Item panel
* @author    Wondwosen Desalegn
* @copyright (c) 2017, Cybersoft
* @date      November 01, 2017
* @namespace Ext.erp.iffs.ux.customer
* @class     Ext.erp.iffs.ux.customer.Panel
* @extends   Ext.Panel
*/
Ext.erp.iffs.ux.customer.Panel = function (config) {
    Ext.erp.iffs.ux.customer.Panel.superclass.constructor.call(this, Ext.apply({
        layout: 'fit',
        border: false,
        tbar: {
            xtype: 'toolbar',
            items: [{
                xtype: 'button',
                text: 'Add',
                iconCls: 'icon-add',
                disabled: !Ext.erp.iffs.ux.Reception.getPermission('Customer', 'CanAdd'),
                handler: this.onAddClick
            }, {
                xtype: 'tbseparator'
            }, {
                xtype: 'button',
                text: 'Edit',
                iconCls: 'icon-edit',
                disabled: !Ext.erp.iffs.ux.Reception.getPermission('Customer', 'CanEdit'),
                handler: this.onEditClick
            }, {
                xtype: 'tbseparator'
            }, {
                xtype: 'button',
                text: 'Delete',
                iconCls: 'icon-delete',
                disabled: !Ext.erp.iffs.ux.Reception.getPermission('Customer', 'CanDelete'),
                handler: this.onDeleteClick
            }, {
                xtype: 'tbfill'
            }, {
                xtype: 'textfield',
                id: 'customer.searchText',
                emptyText: 'Type search text here',
                submitEmptyText: false,
                enableKeyEvents: true,
                style: {
                    borderRadius: '25px',
                    padding: '0 10px',
                    width: '300px'
                },
                listeners: {
                    specialkey: function (field, e) {
                        if (e.getKey() == e.ENTER) {
                            var grid = Ext.getCmp('customer-grid');
                            grid.store.baseParams['record'] = Ext.encode({ searchText: field.getValue() });
                            grid.store.load({ params: { start: 0, limit: grid.pageSize } });
                        }
                    },
                    keyup: function (field, e) {
                        if (field.getValue() == '') {
                            var grid = Ext.getCmp('customer-grid');
                            grid.store.baseParams['record'] = Ext.encode({ searchText: field.getValue() });
                            grid.store.load({ params: { start: 0, limit: grid.pageSize } });
                        }
                    }
                }
            }, {
                xtype: 'tbseparator'
            }, {
                xtype: 'button',
                text: '',
                iconCls: 'icon-excel',
                handler: function () {
                    var searchText = Ext.getCmp('customer.searchText').getValue();
                    window.open('Customer/ExportToExcel?st=' + searchText, '', '');
                }
            }]
        }
    }, config));
};
Ext.extend(Ext.erp.iffs.ux.customer.Panel, Ext.Panel, {
    initComponent: function () {
        var grid = new Ext.erp.iffs.ux.customer.Grid();
        this.items = [grid];

        Ext.erp.iffs.ux.customer.Panel.superclass.initComponent.apply(this, arguments);
    },
    onAddClick: function () {
        new Ext.erp.iffs.ux.customer.Window({
            customerId: 0,
            title: 'Add Customer'
        }).show();
    },
    onEditClick: function () {
        var grid = Ext.getCmp('customer-grid');
        if (!grid.getSelectionModel().hasSelection()) {
            Ext.MessageBox.show({
                title: 'Select',
                msg: 'You must select a record to edit.',
                buttons: Ext.Msg.OK,
                icon: Ext.MessageBox.INFO,
                scope: this
            });
            return;
        }
        var id = grid.getSelectionModel().getSelected().get('Id');
        new Ext.erp.iffs.ux.customer.Window({
            customerId: id,
            title: 'Edit Customer'
        }).show();
    },
    onDeleteClick: function () {
        var grid = Ext.getCmp('customer-grid');
        if (!grid.getSelectionModel().hasSelection()) {
            Ext.MessageBox.show({
                title: 'Select',
                msg: 'You must select a record to delete.',
                buttons: Ext.Msg.OK,
                icon: Ext.MessageBox.INFO,
                scope: this
            });
            return;
        }
        Ext.MessageBox.show({
            title: 'Delete',
            msg: 'Are you sure you want to delete the selected record',
            buttons: {
                ok: 'Yes',
                no: 'No'
            },
            icon: Ext.MessageBox.QUESTION,
            scope: this,
            animEl: 'Delete',
            fn: function (btn) {
                if (btn == 'ok') {
                    var id = grid.getSelectionModel().getSelected().get('Id');
                    Customer.Delete(id, function (result, response) {
                        Ext.getCmp('customer-paging').doRefresh();
                    }, this);
                }
            }
        });
    }
});
Ext.reg('customer-panel', Ext.erp.iffs.ux.customer.Panel);